# Generated by Django 4.2.21 on 2025-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='file',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='graded',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
